name: CI
on:
  pull_request:
    branches: [ main ]   # run on PRs into main
jobs:
  build:                  # <- this job name becomes the check name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Basic check passed"
