name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Connection to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ec2-user
      run: |
        echo "=== CONNECTION TEST ==="
        echo "Target host: $HOSTNAME"
        echo "Username: $USER_NAME"
        
        # Test basic connectivity
        echo "Testing ping..."
        ping -c 2 $HOSTNAME || echo "Ping failed"
        
        echo "Testing SSH port..."
        nc -z -v $HOSTNAME 22 || echo "SSH port not accessible"
        
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        echo "SSH key format check:"
        echo "First line: $(head -n 1 ~/.ssh/id_rsa)"
        echo "Last line: $(tail -n 1 ~/.ssh/id_rsa)"
        echo "Key length: $(wc -l < ~/.ssh/id_rsa) lines"
        
        # Test SSH with detailed output
        echo "Attempting SSH connection..."
        ssh -v -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${USER_NAME}@${HOSTNAME} echo "SUCCESS: SSH connection works!" 2>&1 || echo "SSH connection failed"